DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS education CASCADE;

CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    email VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    user_type VARCHAR(100) NOT NULL DEFAULT 'seeker'
);

CREATE TABLE education (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user_id INT(11),
    name VARCHAR(255) NOT NULL,
    major VARCHAR(255) NOT NULL,
    year_started INT NOT NULL,
    year_graduated INT,
    gpa INT NOT NULL,
    CONSTRAINT fk_education_user FOREIGN KEY (user_id) REFERENCES users (id)
)ENGINE=InnoDB;
